---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=12mm
      - left=16mm
      - right=16mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertinus
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
<!-- TITLE -->
\begin{center}
{\fontsize{35}{50}\selectfont \textbf{Alan J Averett}}
\end{center}

<!-- CONTACT INFO -->
\begin{center} 832.856.4666 | ajaverett0@gmail.com | linkedin.com/in/ajaverett | ajaverett.github.io
\end{center}
\vspace{12pt}

<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Brigham Young University- Idaho}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}B.Sc. Data Science, Statistics; \textit{Major GPA: 3.8/4.0} \end{flushleft}
    \begin{flushright} Apr 2020 - Dec 2023\end{flushright}
  \end{multicols}
  \vspace{-0.25cm}
\end{large}
 * **Certifications**: Web and Computer Programming (3.7/4.0); Machine Learning (4.0/4.0)
 * **Leadership and Awards**: Data Science Society President, SHPE Founding Member, Winner of 3 School-wide Hackathons

\vspace{0.2cm}

<!-- EXPERIENCE : 1ST BULLET-->
\vspace{7pt}

\begin{large}{\bf EXPERIENCE}
\vspace{3pt}
\hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.corecodec.com/}{Corecodec}}\end{flushleft}
    \begin{flushright}San Antonio, TX\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Software Developer Intern}\end
    {flushleft}\begin{flushright}Dec 2023 - Present\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}

- Transformed a manual 5-hour task into a streamlined 10-minute operation by engineering an advanced \textbf{\textit{Python script with Selenium}} to automate the detection of unauthorized use of copyrighted software in mobile applications
- Utilized \textbf{\textit{Pandas}} for efficient data management and analysis for scanning mobile application stores, downloading and extracting data, and \textbf{\textit{automating reports}} to identify key indicators of copyright infringement for software usage

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.familysearch.org}{FamilySearch}}\end{flushleft}
    \begin{flushright}Salt Lake City, UT\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Statistics Intern}\end
    {flushleft}\begin{flushright}Sep 2023 - Dec 2023\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}

* Eliminated 50+ anomalous entities in a worldwide initiative by \textbf{\textit{developing and automating}} in-house tuned anomaly detection methods in \textbf{\textit{Python}} for over 200k+ submissions of unstructured raw survey data
- Frequently delivered summaries of key findings of statistical analyses to the executive team

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://wpaintel.com/about/}{WPA Intelligence}}\end{flushleft}
    \begin{flushright}SE Washington, DC\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Machine Learning Intern}\end{flushleft}
    \begin{flushright}Jul 2022 - Nov 2022\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Created digestible reports for 80+ political campaigns by analyzing/visualizing voter data trends with machine learning models that predicted ideological disposition and turnout using \textbf{\textit{SQL}} and \textbf{\textit{R's tidyverse}}
* Decreased production time (1 hr to 1 min) by building an automated script \textbf{\textit{in SQL and R}} to clean and transform voter data
* Increased accuracy and AUC for all future machine learning models (~ 1-3 percent) by using \textbf{\textit{GIS}} data to categorize over 100 million records of voter data into 12 granularities of population density using \textbf{\textit{R's sf}} and other geospatial libraries


\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://byuidatascience.github.io/lab/}{Mathematics Department BYU-Idaho}}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Teacher's Assistant and Chief Lab Manager}\end{flushleft}
    \begin{flushright}May 2022 - Sep 2023\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Led and coordinated data science society activities and meetings; mentored and supported project teams including weekly bootcamps to teach \textbf{\textit{data analysis/statistics and ML hyper parameter tuning}}, over 6 teams of ~ 6-12 people each
* Managed, and trained all tutors for school-wide DS Lab, teaching \textbf{\textit{Pandas, NumPy, PySpark, SQL}}, in \textbf{\textit{DataBricks}} 
* Tutored Business Stats, DS Programming, Data Wrangling and Viz., Big Data Programming, and Linear Algebra courses in \textbf{\textit{Python (Pandas, PySpark, Sklearn, NumPy, SymPy), R (tidyverse), SQL, and Excel}} to 100+ students
\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{lspoly.com}{Lone Star Polypac}}\end{flushleft}
    \begin{flushright}Wimberly, TX\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Technical Aide}\end
    {flushleft}\begin{flushright}June 2021 - April 2022\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}

\vspace{7pt}

\begin{large}
  {\bf CONSULTING}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://github.com/wilfordwoodruff}{Wilford Woodruff Papers}}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Scientist}\end
    {flushleft}\begin{flushright}May 2023 - Dec 2023\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Provided actionable graphs and trends using \textbf{\textit{NLP}} tools including \textbf{\textit{sentiment analysis}} and unsupervised textual clustering alongside \textbf{\textit{time-series analysis}} as part of the Wilford Woodruff production team in Python
* Delivered an \textbf{\textit{interactive web app}} that cross-referenced religious texts with 19th century published journal entries by using a Bag-of-Words model to vectorize n-grams to find textual matches sorted by confidence using \textbf{\textit{Python's sklearn library}}
* Created similarity algorithm by topic to model recommendations to increase user interaction time with company website


\vspace{7pt}

<!-- SKILLS -->
\begin{large}{\bf SKILLS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}
\vspace{6pt}
* **Python**: Pandas, NumPy, Sci-kit Learn, PySpark, Polars, Keras / Tensorflow, BeautifulSoup4, DataBricks
\vspace{2pt}
* **R**: CAR, Mosaic, RMarkdown, Tidyverse (dplyr, tidyr, stringr, forcats, lubridate, purrr, etc.) 
\vspace{2pt}
* **Visualization libraries**: Streamlit, ggplot2, Matplotlib / Seaborn, Plotly Express, Altair
\vspace{2pt}
* **Other Technical Skills**: Excel, Visual Basic for App. 
(VBA), SQL, MySQL, Git/GitHub, Quarto, LaTeX, Regex, Docker
\vspace{2pt}