project:
  type: website

website:
  title: "Aj Averett's Website"
  navbar:
    left:
      - href: index.qmd
        text: Navigation

format:
  html:
    theme: guide
    css: styles.css
    toc: true



